### ISSUE TITLE
Elasticsearch DEB URLs have changed

### ISSUE THREAD

**Issue by mark-at-nuna** [pelias/packer-elasticsearch#7]
**Describe the bug**
The `scripts/elasticsearch.sh` script is trying to retrieve DEB packages from URLs that do not work and return 404.

It tries to retrieve, for example, `https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1.deb` when the correct URL would be `https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-amd64.deb`.

You just have to append a hyphen and the architecture to the end of the filename.

**Steps to Reproduce**
`packer build -var-file=variables.json pelias-elasticsearch.json`

**Expected behavior**
An AMI would be built.

**Pastebin/Screenshots**
```
==> amazon-ebs: + wget https://artifacts.elastic.co/downloads/elasticsearch/elas
ticsearch-7.5.1.deb
==> amazon-ebs: --2020-08-12 15:22:56--  https://artifacts.elastic.co/downloads/
elasticsearch/elasticsearch-7.5.1.deb
==> amazon-ebs: Resolving artifacts.elastic.co (artifacts.elastic.co)... 199.232.66.222, 2a04:4e42:3b::734
==> amazon-ebs: Connecting to artifacts.elastic.co (artifacts.elastic.co)|199.232.66.222|:443... connected.
==> amazon-ebs: HTTP request sent, awaiting response... 404 Not Found
==> amazon-ebs: 2020-08-12 15:22:56 ERROR 404: Not Found.
```

### References
[Correct download URLs are found here.](https://www.elastic.co/downloads/elasticsearch)

**Comment by orangejulius** [comment]
Ugh. Thanks @mark-at-nuna for reporting this.

Elastic has a nasty habit of breaking build artifacts in various ways and not caring to fix it at all, or consider all the scripts that were working fine but are now broken. For example see https://github.com/elastic/elasticsearch/issues/49599 which also affected Pelias.

If you want to open a PR to fix this we'd be happy to accept it, otherwise we'll get to this soon.

**Comment by missinglink** [comment]
Was this issue resolved in this commit? https://github.com/pelias/packer-elasticsearch/commit/9370537326893b117bec58d020cd93eb8ed61ebb

It seems that we now append the architecture to the 'elasticsearch_version' variable but maybe we just need to update [the README](https://github.com/pelias/packer-elasticsearch#setup-instructions) to reflect that change?
